pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = "us-east-1"
    TF_WORKING_DIR     = "infra/terraform"
  }

  options {
    disableConcurrentBuilds()
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: 'https://github.com/Vin22-03/HealOps-SelfHealing-AWS.git',
            credentialsId: 'githubcreds'
          ]]
        ])
      }
    }

    stage('Terraform Init') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-healops']
        ]) {
          sh """
            cd ${TF_WORKING_DIR}
            terraform init -input=false
          """
        }
      }
    }

    stage('Terraform Format & Validate') {
      steps {
        sh """
          cd ${TF_WORKING_DIR}
          terraform fmt -check
          terraform validate
        """
      }
    }

    stage('Terraform Plan') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-healops']
        ]) {
          sh """
            cd ${TF_WORKING_DIR}
            terraform plan -out=tfplan -input=false
          """
        }
      }
    }

    stage('Manual Approval') {
      steps {
        input message: '🚨 Apply Terraform plan for HealOps? This will create AWS resources.',
              ok: 'Apply'
      }
    }

    stage('Terraform Apply') {
      steps {
        withCredentials([
          [$class: 'AmazonWebServicesCredentialsBinding',
           credentialsId: 'aws-healops']
        ]) {
          sh """
            cd ${TF_WORKING_DIR}
            terraform apply -input=false tfplan
          """
        }
      }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'infra/terraform/tfplan', fingerprint: true
      echo "✅ HealOps infrastructure applied successfully via approved plan"
    }

    failure {
      echo "❌ HealOps pipeline failed. No partial apply occurred."
    }
  }
}
